version: '3.9'

services:
  #exam-archive:
  #  image: tkoalydocker/exam-archive-new
  #  build: ./
  #  environment:
  #    NODE_ENV: development
  #    # Set the key for yourself, as env_file doesn't do multiline
  #    # AWS_CF_KEY: > ---- BEGIN RSA PRIVAE KEY ----
  #  env_file:
  #    - .env.docker
  #  ports:
  #    - 9001:9001
  #  depends_on:
  #    - db

  s3:
    build:
      context: ./docker
      dockerfile: minio.Dockerfile
    environment:
      INITIAL_BUCKETS: 'local/exam-archive-local'
      MINIO_ROOT_USER: tarpisto
      MINIO_ROOT_PASSWORD: tarpisto
    volumes:
      - exam-archive-minio-data:/data
    ports:
      - 127.0.0.1::9000
      - 127.0.0.1::9001

  db:
    image: postgres:15.2-alpine
    ports:
      - '127.0.0.1::5432'
    environment:
      - POSTGRES_PASSWORD=tarpisto
      - POSTGRES_USER=tarpisto
      - POSTGRES_DB=tarpisto
      - PGDATA=/data/pgdata
    volumes:
      - exam-archive-pg-data:/data/pgdata

  adminer:
    image: adminer:4.8.1-standalone
    ports:
      - 127.0.0.1:9003:8080

volumes:
  exam-archive-pg-data:
  exam-archive-minio-data:
