version: '3.9'

services:
  #exam-archive:
  #  image: tkoalydocker/exam-archive-new
  #  build: ./
  #  environment:
  #    NODE_ENV: development
  #    # Set the key for yourself, as env_file doesn't do multiline
  #    # AWS_CF_KEY: > ---- BEGIN RSA PRIVAE KEY ----
  #  env_file:
  #    - .env.docker
  #  ports:
  #    - 9001:9001
  #  depends_on:
  #    - db

  s3:
    build:
      context: ./docker
      dockerfile: minio.Dockerfile
    environment:
      INITIAL_BUCKETS: 'local/exam-archive-local'
    volumes:
      - exam-archive-minio-data:/data
    ports:
      - 127.0.0.1:9001:9000
      - 127.0.0.1:9002:9001

  db:
    image: postgres:11.7
    ports:
      - '127.0.0.1:9876:5432'
    environment:
      - POSTGRES_PASSWORD=Su5hgVvoqUCRw5vrWmrW
      - POSTGRES_USER=tarpisto
      - POSTGRES_DB=tarpisto
      - PGDATA=/data/pgdata
    volumes:
      - exam-archive-pg-data:/data/pgdata

  adminer:
    image: adminer
    ports:
      - 127.0.0.1:9003:8080

volumes:
  exam-archive-pg-data:
  exam-archive-minio-data:
