version: '3.9'

services:
  db:
    networks:
      - security

  s3:
    networks:
      - security

  tarpisto:
    image: tarpisto/tarpisto:latest
    healthcheck:
      test: ['CMD', 'curl', '-f', 'http://localhost:9000/api/health']
      interval: 5s
      timeout: 5s
      retries: 5
    depends_on:
      db:
        condition: service_healthy
      s3:
        condition: service_healthy
    environment:
      - PORT=9000
      - PG_CONNECTION_STRING=postgresql://tarpisto:tarpisto@db:5432/tarpisto
      - COOKIE_NAME=${COOKIE_NAME}
      - COOKIE_SECRET=${COOKIE_SECRET}
      - COOKIE_ISSUER=${COOKIE_ISSUER}
      - COOKIE_SUBJECT=${COOKIE_SUBJECT}
      - COOKIE_JWTID=${COOKIE_JWTID}
      - USER_SERVICE_SERVICE_ID=${USER_SERVICE_SERVICE_ID}
      - USER_SERVICE_URL=${USER_SERVICE_URL}
      - AWS_REGION=${AWS_REGION}
      - AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID}
      - AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY}
      - AWS_S3_ENDPOINT=http://s3:9000
      - AWS_S3_FORCE_PATH_STYLE=${AWS_S3_FORCE_PATH_STYLE}
      - AWS_S3_BUCKET_ID=${AWS_S3_BUCKET_ID}
      - APP_ENV=development
    ports:
      - 127.0.0.1::9000
    networks:
      - security

  security:
    image: ghcr.io/zaproxy/zaproxy:stable
    volumes:
      - $PWD:/zap/wrk/:rw
    depends_on:
      tarpisto:
        condition: service_healthy
    command: zap.sh -cmd -autorun /zap/wrk/zap.yaml
    networks:
      - security

networks:
  security:
    name: exam-archive-new-security
