version: '3'

services:
  backend:
    image: tko-aly/exam-archive-backend
    build: './backend'
    restart: unless-stopped
    ports:
      - '9001:9001'
    environment:
      - PG_CONNECTION_STRING=postgresql://tarpisto:Su5hgVvoqUCRw5vrWmrW@db:5432/tarpisto
      - NODE_ENV=production
      - PORT=9001
      - ARCHIVE_FILE_DIR=/data/tarpisto/files
    volumes:
      - ./files:/data/tarpisto/files
    depends_on:
      - db

  db:
    image: postgres:11.1
    restart: unless-stopped
    ports:
      - '9876:5432'
    environment:
      - POSTGRES_PASSWORD=Su5hgVvoqUCRw5vrWmrW
      - POSTGRES_USER=tarpisto
      - POSTGRES_DB=tarpisto
      - PGDATA=/data/pgdata
    volumes:
      - pg-data:/data/pgdata

volumes:
  pg-data:
