version: '3'

services:
  exam-archive:
    image: tkoalydocker/exam-archive-new
    build: ./
    environment:
      - NODE_ENV=development
      # Set the key for yourself, as env_file doesn't do multiline
      # AWS_CF_KEY: > ---- BEGIN RSA PRIVAE KEY ----
    env_file:
      - .env.docker
    ports:
      - 9001:9001
    depends_on:
      - db

  db:
    image: postgres:11.1
    ports:
      - '9876:5432'
    environment:
      - POSTGRES_PASSWORD=Su5hgVvoqUCRw5vrWmrW
      - POSTGRES_USER=tarpisto
      - POSTGRES_DB=tarpisto
      - PGDATA=/data/pgdata
    volumes:
      - exam-archive-pg-data:/data/pgdata

  adminer:
    image: adminer
    ports:
      - 8082:8080

volumes:
  exam-archive-pg-data:
