name: E2E Testing
on:
  push:
    branches: [master]
  pull_request:
    branches: [master]
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Run tests
        run: ./run-tests.sh
      - name: Upload screenshots and videos
        if: always()
        uses: actions/upload-artifact@v3
        with:
          name: playwright-results
          path: test-results/playwright
      - name: Upload accessibility reports
        if: always()
        uses: actions/upload-artifact@v3
        with:
          name: axe-reports
          path: test-results/axe-reports
